apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: sknamespace
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: dotnetdemo-myapp-1
        image: dockerregister1.azurecr.io/dotnetdemo-myapp
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: sk  