apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: sknamespace
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: dotnetdemo-myapp-1
        image: dotnetdemo-myapp
        ports:
        - containerPort: 5000