apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: sknamespace
spec:
  selector:
    app.kubernetes.io/name: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: Loadbalancer    